# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KhebraTechnician' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~>5.4.1'
  pod 'GoogleMaps', '4.1.0'
  pod 'GooglePlaces'

  # Pods for KhebraTechnician

  target 'KhebraTechnicianTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KhebraTechnicianUITests' do
    # Pods for testing
  end

end
